name: Create issue on commit
on:
  pull_request:
    paths: ['*', '.github/**']

permissions:
  pull-requests: write

env:
  NUMBER: ${{ github.event.number }}
  REVIEWERS: '["veertest-review"]'
  LABELS: '["Framework Changes"]'

jobs:
  assign-reviewers-and-labels:
    name: Assign T2 Reviewers and Labels to the PR
    runs-on: ubuntu-latest
    steps:
      - name: Add Labels to the PR
        run: |
          echo "Adding applicable labels to the PR $NUMBER"
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CHERRYPICK_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/issues/$NUMBER/labels \
          -d '{"labels": '"$LABELS"'}'
